### ISSUE TITLE
Can't access StreamChat.Libs.Ilogs

### ISSUE THREAD

**Issue by chrmeehansr** [GetStream/stream-chat-dotnet-maui#10]
Novice developer, learning w/ .NET MAUI & C# so forgive my ignorance. I've pulled down the sample, ensured stream-chat-net is installed in VS 2022 (https://github.com/GetStream/stream-chat-net), setup a free account on Stream w/ API key, etc..

Only issue I'm presented with when trying to build and learn via the sample is accessing Ilogs as part of the StreamChat.Libs namespace. All others are referencable as expected.  I've tried to trace it through the entire project but being a novice have hit a wall. Nothing modified but hit with this issue trying to successfully build after opening the solution. 

Thanks in advance. A couple of errors referenced below but 48 in total. 

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0234	The type or namespace name 'Logs' does not exist in the namespace 'StreamChat.Libs' (are you missing an assembly reference?)	StreamChatMaui (net7.0-android), StreamChatMaui (net7.0-ios), StreamChatMaui (net7.0-maccatalyst), StreamChatMaui (net7.0-windows10.0.19041.0)	...\stream-chat-dotnet-maui\StreamChatMaui\Plugins\stream-chat-dotnet-sdk\Core\LowLevelClient\API\Internal\InternalApiClientBase.cs	10		

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0246	The type or namespace name 'ILogs' could not be found (are you missing a using directive or an assembly reference?)	StreamChatMaui (net7.0-android), StreamChatMaui (net7.0-ios), StreamChatMaui (net7.0-maccatalyst), StreamChatMaui (net7.0-windows10.0.19041.0)	...\stream-chat-dotnet-maui\StreamChatMaui\Plugins\stream-chat-dotnet-sdk\Core\LowLevelClient\API\Internal\InternalMessageApi.cs	14

**Comment by sierpinskid** [comment]
Hi @chrmeehansr 
Thank you for reporting this issue! There was a bug in the .gitignore file, and the Logs directory was wrongly excluded from the repository. I've just pushed a fix for this. Please let me know if this resolves your issue.

The .NET SDK you've mentioned - [stream-chat-net](https://github.com/GetStream/stream-chat-net) - is for server-side chat management. We have separate SDKs for the client side and the server side. In short, the client-side maintains a WebSocket connection to receive real-time updates, whereas the server-side SDK is for administrative purposes. This .NET MAUI example is using our [Unity SDK](https://github.com/GetStream/stream-chat-unity) after conversion, and at the moment, it's only available here [stream-chat-dotnet-sdk](https://github.com/GetStream/stream-chat-dotnet-maui/tree/main/StreamChatMaui/Plugins/stream-chat-dotnet-sdk)

`Novice developer, learning w/ .NET MAUI & C#` Good luck, and thank you for your contribution!
